package in.tekathon.common;
// Generated Jan 22, 2017 3:39:42 PM by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer employeeid;
     private String firstname;
     private String lastname;
     private String username;
     private String password;
     private String street;
     private String city;
     private String state;
     private String pincode;
     private String country;
     private String emailid;
     private String contactno;
     private String dateofbirth;
     private String designation;
     private String dateofjoining;
     private Integer yearsofexperience;
     private Integer reportingmanagerId;
     private Float casualLeaves;
     private Integer earnedLeaves;
     private Integer sickLeaves;
     private Integer compOffs;
     private Integer sharedLeaves;

    public Employee() {
    }

    public Employee(String firstname, String lastname, String username, String password, String street, String city, String state, String pincode, String country, String emailid, String contactno, String dateofbirth, String designation, String dateofjoining, Integer yearsofexperience, Integer reportingmanagerId, Float casualLeaves, Integer earnedLeaves, Integer sickLeaves, Integer compOffs, Integer sharedLeaves) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.username = username;
       this.password = password;
       this.street = street;
       this.city = city;
       this.state = state;
       this.pincode = pincode;
       this.country = country;
       this.emailid = emailid;
       this.contactno = contactno;
       this.dateofbirth = dateofbirth;
       this.designation = designation;
       this.dateofjoining = dateofjoining;
       this.yearsofexperience = yearsofexperience;
       this.reportingmanagerId = reportingmanagerId;
       this.casualLeaves = casualLeaves;
       this.earnedLeaves = earnedLeaves;
       this.sickLeaves = sickLeaves;
       this.compOffs = compOffs;
       this.sharedLeaves = sharedLeaves;
    }
   
    public Integer getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getContactno() {
        return this.contactno;
    }
    
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }
    public String getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(String dateofbirth) {
        this.dateofbirth = dateofbirth;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getDateofjoining() {
        return this.dateofjoining;
    }
    
    public void setDateofjoining(String dateofjoining) {
        this.dateofjoining = dateofjoining;
    }
    public Integer getYearsofexperience() {
        return this.yearsofexperience;
    }
    
    public void setYearsofexperience(Integer yearsofexperience) {
        this.yearsofexperience = yearsofexperience;
    }
    public Integer getReportingmanagerId() {
        return this.reportingmanagerId;
    }
    
    public void setReportingmanagerId(Integer reportingmanagerId) {
        this.reportingmanagerId = reportingmanagerId;
    }
    public Float getCasualLeaves() {
        return this.casualLeaves;
    }
    
    public void setCasualLeaves(Float casualLeaves) {
        this.casualLeaves = casualLeaves;
    }
    public Integer getEarnedLeaves() {
        return this.earnedLeaves;
    }
    
    public void setEarnedLeaves(Integer earnedLeaves) {
        this.earnedLeaves = earnedLeaves;
    }
    public Integer getSickLeaves() {
        return this.sickLeaves;
    }
    
    public void setSickLeaves(Integer sickLeaves) {
        this.sickLeaves = sickLeaves;
    }
    public Integer getCompOffs() {
        return this.compOffs;
    }
    
    public void setCompOffs(Integer compOffs) {
        this.compOffs = compOffs;
    }
    public Integer getSharedLeaves() {
        return this.sharedLeaves;
    }
    
    public void setSharedLeaves(Integer sharedLeaves) {
        this.sharedLeaves = sharedLeaves;
    }




}


